### ISSUE TITLE
Did you try with server-side rendering?

### ISSUE THREAD

**Issue by sneko** [Aymkdn/v-snackbars#22]
Hi @Aymkdn ,

I'm using your plugin with success on a full client oriented Vue.js, but when trying to use server-side rendering (not Nuxt.js but the official SSR) I'm getting from the Vue server:
```
/Uxxxxxxxxxxxx/node_modules/v-snackbars/v-snackbars.vue:1
<template>
^

SyntaxError: Unexpected token '<'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at r (/Uxxxxxxxxxxxx/node_modules/vue-server-renderer/build.dev.js:9315:16)
    at Object.v-snackbars (webpack:/external "v-snackbars":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/ts-loader/index.js?!./node_modules/vuetify-loader/lib/loader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/ErrorsToaster.vue?vue&type=script&lang=ts& (js/app.js:316:69)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/components/ErrorsToaster.vue?vue&type=script&lang=ts& (src/components/ErrorsToaster.vue?429b:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/components/ErrorsToaster.vue (src/components/ErrorsToaster.vue:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
```
which makes a 500 error on the frontend.

* I tried to remove the snackbars from the template, it was failing too
* I thought I would have to use https://github.com/egoist/vue-client-only that works well to not render some components from the server but when I tried to remove the component from my view component (`{ components: VSnackbars }`) and it works well (without your plugin so)

I can continue to investigate but just wanted to know if you did this before?

Thank you,

**Comment by Aymkdn** [comment]
No, I didn't try... Sorry.

**Comment by sneko** [comment]
I succeeded in using it by removing my import from the view component, so there is no:
```
{
  ...,
  components: {
    VSnackbars,
  },
}
```

But instead in my `entry-client.js` file I did the following (registering globally, only when client side):
```
import VSnackbars from 'v-snackbars';
Vue.component('v-snackbars', VSnackbars);
```

_Note: in addition in the template I wrapped the `v-snackbars` with `client-only` to make it not rendered when serving from server, but it has no effect to make it working_

Hope it helps :)

Thank you,

_Note: it looks not proper but that's the way I found on forums when the component is not compatible with SSR out of the box_

**Comment by hyperstown** [comment]
For nuxt users: You can just add this to build options in `nuxt.config.js`:
```js
build: {
    transpile: [
      'v-snackbars',
    ],
}
  ```
